// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLffWmBlOXteEk5SlXenFngQ_9EFozFGg',
    appId: '1:350005315493:web:32c72eb00b7aeb869e8a4c',
    messagingSenderId: '350005315493',
    projectId: 'fuks-app',
    authDomain: 'fuks-app.firebaseapp.com',
    storageBucket: 'fuks-app.appspot.com',
    measurementId: 'G-3XQTG3P798',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXVf_nyxg1FNKxX-p0MVK7qAK8_xItfA',
    appId: '1:350005315493:android:85344055cd6a1c989e8a4c',
    messagingSenderId: '350005315493',
    projectId: 'fuks-app',
    storageBucket: 'fuks-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzkrUxkik7QhLt9hU6K460ggFtAJa11Wo',
    appId: '1:350005315493:ios:018c281fd3b9a8ed9e8a4c',
    messagingSenderId: '350005315493',
    projectId: 'fuks-app',
    storageBucket: 'fuks-app.appspot.com',
    iosClientId: '350005315493-a139j5f5tt10ca8iob7cpi5hoo0fd8p8.apps.googleusercontent.com',
    iosBundleId: 'org.fuks.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzkrUxkik7QhLt9hU6K460ggFtAJa11Wo',
    appId: '1:350005315493:ios:f3380393dffb81ee9e8a4c',
    messagingSenderId: '350005315493',
    projectId: 'fuks-app',
    storageBucket: 'fuks-app.appspot.com',
    iosClientId: '350005315493-9gh00dgk522rpgsji52dbmidaqmhfh7d.apps.googleusercontent.com',
    iosBundleId: 'org.fuks.app.RunnerTests',
  );
}
